export const airlineWebsiteMap = {
  "ANA": "https://www.ana.co.jp",
  "All Nippon Airways": "https://www.ana.co.jp",
  "American Airlines": "https://www.aa.com",
  "Delta Air Lines": "https://www.delta.com",
  "United Airlines": "https://www.united.com",
  "Korean Air": "https://www.koreanair.com",
  "Lufthansa": "https://www.lufthansa.com",
  "Emirates": "https://www.emirates.com",
  "Qatar Airways": "https://www.qatarairways.com",
  "British Airways": "https://www.britishairways.com",
  "Air France": "https://www.airfrance.com",
  "Singapore Airlines": "https://www.singaporeair.com",
  "Turkish Airlines": "https://www.turkishairlines.com",
  "Etihad Airways": "https://www.etihad.com",
  "Cathay Pacific": "https://www.cathaypacific.com",
  "Air Canada": "https://www.aircanada.com",
  "Qantas": "https://www.qantas.com",
  "Swiss International Air Lines": "https://www.swiss.com",
  "KLM Royal Dutch Airlines": "https://www.klm.com",
  "Japan Airlines": "https://www.jal.co.jp",
  "Iberia": "https://www.iberia.com",
  "Alitalia": "https://www.alitalia.com",
  "Thai Airways": "https://www.thaiairways.com",
  "Austrian Airlines": "https://www.austrian.com",
  "Aeromexico": "https://www.aeromexico.com",
  "Asiana Airlines": "https://flyasiana.com",
  "Eva Air": "https://www.evaair.com",
  "Scandinavian Airlines": "https://www.flysas.com",
  "Finnair": "https://www.finnair.com",
  "Vietnam Airlines": "https://www.vietnamairlines.com",
  "Philippine Airlines": "https://www.philippineairlines.com",
  "Hawaiian Airlines": "https://www.hawaiianairlines.com",
  "Air New Zealand": "https://www.airnewzealand.com",
  "Southwest Airlines": "https://www.southwest.com",
  "JetBlue Airways": "https://www.jetblue.com",
  "Alaska Airlines": "https://www.alaskaair.com",
  "Spirit Airlines": "https://www.spirit.com",
  "Ryanair": "https://www.ryanair.com",
  "EasyJet": "https://www.easyjet.com",
  "Norwegian Air": "https://www.norwegian.com",
  "Wizz Air": "https://wizzair.com",
  "AirAsia": "https://www.airasia.com",
  "IndiGo": "https://www.goindigo.in",
  "Vistara": "https://www.airvistara.com",
  "SpiceJet": "https://www.spicejet.com",
  "Saudia": "https://www.saudia.com",
  "El Al": "https://www.elal.com",
  "Aegean Airlines": "https://en.aegeanair.com",
  "Pegasus Airlines": "https://www.flypgs.com",
  "TAP Air Portugal": "https://www.flytap.com",
  "AeroMexico": "https://www.aeromexico.com",
  "VivaAerobus": "https://www.vivaaerobus.com",
  "Volaris": "https://www.volaris.com/"
};