export const fuzzyAirlineWebsiteMap = {
  "ana": "https://www.ana.co.jp",
  "all nippon airways": "https://www.ana.co.jp",
  "all nippon ways": "https://www.ana.co.jp",
  "american airlines": "https://www.aa.com",
  "american": "https://www.aa.com",
  "american lines": "https://www.aa.com",
  "aeromexico":"https://www.aeromexico.com",
  "aemexico":"https://www.aeromexico.com",
  "delta":" https://www.delta.com",
  "Delta":" https://www.delta.com",
  "delta air lines": "https://www.delta.com",
  "delta  lines": "https://www.delta.com",
  "united airlines": "https://www.united.com",
  "united": "https://www.united.com",
  "united lines": "https://www.united.com",
  "korean air": "https://www.koreanair.com",
  "korean": "https://www.koreanair.com",
  "lufthansa": "https://www.lufthansa.com",
  "emirates": "https://www.emirates.com",
  "qatar airways": "https://www.qatarairways.com",
  "qatar ways": "https://www.qatarairways.com",
  "british airways": "https://www.britishairways.com",
  "british ways": "https://www.britishairways.com",
  "air france": "https://www.airfrance.com",
  "france": "https://www.airfrance.com",
  "singapore airlines": "https://www.singaporeair.com",
  "singapore": "https://www.singaporeair.com",
  "singapore lines": "https://www.singaporeair.com",
  "turkish airlines": "https://www.turkishairlines.com",
  "turkish": "https://www.turkishairlines.com",
  "turkish lines": "https://www.turkishairlines.com",
  "etihad airways": "https://www.etihad.com",
  "etihad ways": "https://www.etihad.com",
  "cathay pacific": "https://www.cathaypacific.com",
  "air canada": "https://www.aircanada.com",
  "canada": "https://www.aircanada.com",
  "qantas": "https://www.qantas.com",
  "swiss international air lines": "https://www.swiss.com",
  "swiss international  lines": "https://www.swiss.com",
  "swiss  air lines": "https://www.swiss.com",
  "klm royal dutch airlines": "https://www.klm.com",
  "klm royal dutch": "https://www.klm.com",
  "klm royal dutch lines": "https://www.klm.com",
  "japan airlines": "https://www.jal.co.jp",
  "japan lines": "https://www.jal.co.jp",
  "iberia": "https://www.iberia.com",
  "alitalia": "https://www.alitalia.com",
  "thai airways": "https://www.thaiairways.com",
  "thai ways": "https://www.thaiairways.com",
  "austrian airlines": "https://www.austrian.com",
  "austrian": "https://www.austrian.com",
  "austrian lines": "https://www.austrian.com",
  "aeromexico": "https://www.aeromexico.com",
  "asiana airlines": "https://flyasiana.com",
  "asiana": "https://flyasiana.com",
  "asiana lines": "https://flyasiana.com",
  "eva air": "https://www.evaair.com",
  "eva": "https://www.evaair.com",
  "scandinavian airlines": "https://www.flysas.com",
  "scandinavian": "https://www.flysas.com",
  "scandinavian lines": "https://www.flysas.com",
  "finnair": "https://www.finnair.com",
  "vietnam airlines": "https://www.vietnamairlines.com",
  "vietnam": "https://www.vietnamairlines.com",
  "vietnam lines": "https://www.vietnamairlines.com",
  "philippine airlines": "https://www.philippineairlines.com",
  "philippine": "https://www.philippineairlines.com",
  "philippine lines": "https://www.philippineairlines.com",
  "hawaiian airlines": "https://www.hawaiianairlines.com",
  "hawaiian": "https://www.hawaiianairlines.com",
  "hawaiian lines": "https://www.hawaiianairlines.com",
  "air new zealand": "https://www.airnewzealand.com",
  "new zealand": "https://www.airnewzealand.com",
  "southwest airlines": "https://www.southwest.com",
  "southwest": "https://www.southwest.com",
  "southwest lines": "https://www.southwest.com",
  "jetblue airways": "https://www.jetblue.com",
  "jetblue ways": "https://www.jetblue.com",
  "alaska airlines": "https://www.alaskaair.com",
  "alaska": "https://www.alaskaair.com",
  "alaska lines": "https://www.alaskaair.com",
  "spirit airlines": "https://www.spirit.com",
  "spirit": "https://www.spirit.com",
  "spirit lines": "https://www.spirit.com",
  "ryanair": "https://www.ryanair.com",
  "easyjet": "https://www.easyjet.com",
  "norwegian air": "https://www.norwegian.com",
  "norwegian": "https://www.norwegian.com",
  "wizz air": "https://wizzair.com",
  "wizz": "https://wizzair.com",
  "airasia": "https://www.airasia.com",
  "asia": "https://www.airasia.com",
  "indigo": "https://www.goindigo.in",
  "vistara": "https://www.airvistara.com",
  "spicejet": "https://www.spicejet.com",
  "saudia": "https://www.saudia.com",
  "el al": "https://www.elal.com",
  "aegean airlines": "https://en.aegeanair.com",
  "aegean": "https://en.aegeanair.com",
  "aegean lines": "https://en.aegeanair.com",
  "pegasus airlines": "https://www.flypgs.com",
  "pegasus": "https://www.flypgs.com",
  "pegasus lines": "https://www.flypgs.com",
  "tap air portugal": "https://www.flytap.com",
  "tap  portugal": "https://www.flytap.com",
  "jal": "https://www.jal.co.jp",
  "ua": "https://www.united.com",
  "aa": "https://www.aa.com",
  "ba": "https://www.britishairways.com",
  "dl": "https://www.delta.com",
  "klm": "https://www.klm.com",
  "lx": "https://www.swiss.com",
  "ek": "https://www.emirates.com",
  "qr": "https://www.qatarairways.com",
  "lh": "https://www.lufthansa.com",
  "af": "https://www.airfrance.com"
};